#!/usr/bin/env python3
"""Verify that all documents are properly indexed in Meilisearch."""

import os
import sys
import meilisearch
from dotenv import load_dotenv
from rich.console import Console
from rich.table import Table

load_dotenv()

console = Console()

# Expected counts
EXPECTED_COUNTS = {
    "StoreKit": 1310,
    "MerchantTokenNotificationServices": 10,
    "UniformTypeIdentifiers": 191,
    "Xcode": 332,
    "ContactProvider": 103,
    "PencilKit": 301,
    "HTTP-Live-Streaming": 22,
    "AccountDataTransfer": 17,
    "CoreWLAN": 235,
    "vmnet": 97,
    "MailKit": 177,
    "MediaPlayer": 712,
    "tvos-release-notes": 49,
    "Collaboration": 39,
    "SensitiveContentAnalysis": 35,
    "SystemConfiguration": 640,
    "AppDataTransfer": 17,
    "ManagedAppDistribution": 1658,
    "SensorKit": 522,
    "WebKit": 2903,
    "ImageCaptureCore": 683,
    "ShaderGraph": 248,
    "QuickLookUI": 60,
    "LatentSemanticMapping": 72,
    "EventKit": 407,
    "AudioToolbox": 3548,
    "SecurityInterface": 133,
    "JavaScriptCore": 335,
    "CoreTelephony": 103,
    "LiveCommunicationKit": 273,
    "coreservices": 4713,
    "CoreImage": 850,
    "IOUSBHost": 499,
    "PHASE": 481,
    "Accelerate": 8625,
    "ClassKitCatalogAPI": 20,
    "playgroundsupport": 73,
    "Messages": 145,
    "NotaryAPI": 25,
    "technologies": 1,
    "HomeKit": 1286,
    "NetworkExtension": 1123,
    "ServiceManagement": 51,
    "WidgetKit": 316,
    "FamilyControls": 2396,
    "CoreAudioKit": 61,
    "GSS": 365,
    "EventKitUI": 51,
    "IdentityLookup": 115,
    "TVUIKit": 126,
    "AutomaticAssessmentConfiguration": 67,
    "SCSIPeripheralsDriverKit": 76,
    "FinanceKit": 347,
    "MediaAccessibility": 89,
    "Virtualization": 502,
    "AdvancedCommerceAPI": 191,
    "ColorSync": 256,
    "SwiftData": 868,
    "PassKit": 1063,
    "NaturalLanguage": 293,
    "VideoSubscriberAccount": 138,
    "MediaSetup": 18,
    "CloudKit": 950,
    "StoreKitTest": 250,
    "AppClip": 34,
    "CoreGraphics": 1716,
    "CarPlay": 807,
    "Synchronization": 222,
    "Combine": 10801,
    "MetalPerformanceShadersGraph": 778,
    "QuickLook": 156,
    "PermissionKit": 996,
    "metalperformanceshaders": 2942,
    "XcodeKit": 37,
    "LivePhotosKitJS": 57,
    "xcselect": 1,
    "Technotes": 69,
    "IOBluetoothUI": 111,
    "SiriKit": 37,
    "Translation": 92,
    "RosterAPI": 21,
    "USBSerialDriverKit": 15,
    "Metal": 3720,
    "VisionKit": 245,
    "CoreBluetooth": 361,
    "snapshots": 11,
    "Distributed": 135,
    "Security": 5168,
    "ManagedSettingsUI": 21,
    "AdSupport": 5,
    "AVRouting": 37,
    "macos-release-notes": 54,
    "BrowserEngineKit": 517,
    "AssetsLibrary": 126,
    "DeviceCheck": 32,
    "TouchControls": 359,
    "AppStoreServerNotifications": 111,
    "XCTest": 439,
    "HealthKit": 2021,
    "CloudKitJS": 343,
    "RoomPlan": 518,
    "GameKit": 1054,
    "UIKit": 11000,
    "BundleResources": 832,
    "GroupActivities": 505,
    "WalletOrders": 31,
    "AppleNews": 60,
    "PackageDescription": 553,
    "ScreenTime": 28,
    "AppLicenseDeliverySDK": 49,
    "Dispatch": 354,
    "SiriKitCloudMedia": 168,
    "MessageUI": 80,
    "IOSurface": 216,
    "AlarmKit": 264,
    "Contacts": 668,
    "UserNotificationsUI": 20,
    "ScreenSaver": 20,
    "iokit": 581,
    "LightweightCodeRequirements": 312,
    "GLKit": 515,
    "Network": 1836,
    "ClockKit": 589,
    "CoreTransferable": 92,
    "DeviceDiscoveryUI": 34,
    "TelephonyMessagingKit": 1005,
    "TipKit": 183,
    "AppIntents": 6527,
    "WorkoutKit": 290,
    "CKToolJS": 534,
    "SecureElementCredential": 149,
    "SigninwithApple": 7,
    "PDFKit": 713,
    "VisualIntelligence": 19,
    "SceneKit": 1567,
    "CoreLocationUI": 28,
    "iTunesLibrary": 279,
    "Charts": 598,
    "TabletopKit": 627,
    "DockKit": 364,
    "ImmersiveMediaSupport": 394,
    "AdServices": 15,
    "Foundation": 12374,
    "ActivityKit": 346,
    "PaperKit": 208,
    "TechnologyOverviews": 31,
    "SecurityFoundation": 10,
    "HIDDriverKit": 2749,
    "LocalAuthenticationEmbeddedUI": 8,
    "DeviceActivity": 1022,
    "Matter": 24186,
    "installer_js": 51,
    "CoreData": 1029,
    "LinkPresentation": 38,
    "WeatherKit": 1329,
    "RegexBuilder": 503,
    "SharedWithYou-technology": 0,
    "applicationservices": 3488,
    "Vision": 1794,
    "CoreVideo": 751,
    "AVFoundation": 4814,
    "hvf": 326,
    "DarwinNotify": 51,
    "ScreenCaptureKit": 281,
    "Updates": 79,
    "AddressBookUI": 68,
    "MediaToolbox": 36,
    "quicktime-file-format": 1152,
    "AppleMusicFeed": 40,
    "AppTrackingTransparency": 10,
    "AppStoreConnectAPI": 5068,
    "USBDriverKit": 926,
    "CreateML": 2649,
    "AdAttributionKit": 92,
    "CryptoTokenKit": 308,
    "AccountOrganizationalDataSharing": 10,
    "Speech": 348,
    "EndpointSecurity": 1564,
    "CoreText": 2327,
    "PushToTalk": 111,
    "Assignables": 1997,
    "BlockStorageDeviceDriverKit": 41,
    "SKAdNetworkforWebAds": 7,
    "LocalAuthentication": 239,
    "ApplePencil": 4,
    "SerialDriverKit": 65,
    "GameplayKit": 437,
    "FoundationModels": 517,
    "CoreML": 720,
    "MetricKit": 228,
    "XCUIAutomation": 593,
    "playgroundbluetooth": 64,
    "apple-silicon": 17,
    "SpriteKit": 1033,
    "apple_search_ads": 251,
    "BrowserKit": 11,
    "JournalingSuggestions": 925,
    "MapKit": 1191,
    "ContactsUI": 50,
    "Testing": 315,
    "ImageIO": 891,
    "professional_video_applications": 5,
    "AppleMapsServerAPI": 48,
    "CoreMIDI": 968,
    "NetworkingDriverKit": 612,
    "safari-developer-tools": 17,
    "Social": 62,
    "SoundAnalysis": 60,
    "System": 609,
    "AVFAudio": 1398,
    "DataDetection": 102,
    "DeviceDiscoveryExtension": 114,
    "CoreAudioTypes": 606,
    "SampleCode": 1,
    "MusicKit": 2888,
    "TabularData": 1670,
    "EnergyKit": 248,
    "SiriEventSuggestionsMarkup": 37,
    "CarKey": 121,
    "GameController": 997,
    "GeoToolbox": 39,
    "DiskArbitration": 147,
    "iAd": 30,
    "MediaExtension": 305,
    "CoreMediaIO": 550,
    "ExecutionPolicy": 25,
    "NotificationCenter": 47,
    "visionOS": 70,
    "ForceFeedback": 326,
    "NearbyInteraction": 129,
    "FinderSync": 33,
    "ReplayKit": 155,
    "CryptoKit": 677,
    "ShazamKit": 146,
    "Cinematic": 202,
    "Automator": 155,
    "FileProviderUI": 19,
    "CoreMedia": 2231,
    "webkitjs": 4928,
    "AGL": 16,
    "ios-ipados-release-notes": 55,
    "Accounts": 78,
    "EnterpriseProgramAPI": 185,
    "WeatherKitRESTAPI": 41,
    "WiFiAware": 286,
    "RealityKit": 4717,
    "ExternalAccessory": 80,
    "Swift": 16148,
    "CoreNFC": 427,
    "AVKit": 428,
    "ClassKit": 177,
    "IdentityDocumentServicesUI": 31,
    "CoreMotion": 411,
    "kernelmanagement": 4,
    "CoreLocation": 401,
    "visionos-release-notes": 11,
    "PreferencePanes": 30,
    "FSKit": 648,
    "IdentityDocumentServices": 101,
    "QuickLookThumbnailing": 64,
    "GameSave": 64,
    "ExtensionKit": 28,
    "Compression": 64,
    "FileProvider": 474,
    "watchos-release-notes": 47,
    "AudioDriverKit": 532,
    "AppleMusicAPI": 438,
    "OSLog": 95,
    "CoreSpotlight": 382,
    "QuartzCore": 667,
    "swift-playgrounds": 24,
    "PCIDriverKit": 352,
    "AddressBook": 582,
    "Symbols": 126,
    "ParavirtualizedGraphics": 110,
    "MetalFX": 240,
    "ARKit": 2056,
    "AppKit": 12000,
    "CoreHID": 3421,
    "PhotoKit": 11,
    "ApplePayontheWeb": 416,
    "analytics-reports": 121,
    "ApplePayWebMerchantRegistrationAPI": 9,
    "MediaLibrary": 212,
    "FinanceKitUI": 1562,
    "AuthenticationServices": 1125,
    "DeclaredAgeRange": 68,
    "MarketplaceKit": 182,
    "Xcode-Release-Notes": 56,
    "WirelessInsights": 67,
    "SafetyKit": 71,
    "os": 232,
    "LockedCameraCapture": 46,
    "AutomatedDeviceEnrollment": 1,
    "MetalKit": 118,
    "MLCompute": 701,
    "VideoToolbox": 786,
    "ThreadNetwork": 26,
    "WatchKit": 725,
    "SafariServices": 220,
    "MultipeerConnectivity": 119,
    "WatchConnectivity": 104,
    "MIDIDriverKit": 160,
    "ExposureNotification": 225,
    "ExternalPurchaseServerAPI": 81,
    "DeveloperToolsSupport": 86,
    "TVServices": 139,
    "Quartz": 702,
    "CreateMLComponents": 5701,
    "ModelIO": 890,
    "CompositorServices": 194,
    "DriverKit": 2860,
    "Spatial": 1364,
    "CoreHaptics": 217,
    "CFNetwork": 416,
    "OpenGLES": 1590,
    "ManagedSettings": 204,
    "AccessorySetupKit": 254,
    "BackgroundAssets": 137,
    "CallKit": 270,
    "WalletPasses": 56,
    "BackgroundTasks": 61,
    "ExceptionHandling": 38,
    "Accessibility": 284,
    "XPC": 390,
    "AutomaticSignInAPI": 5,
    "AppleArchive": 247,
    "SystemExtensions": 82,
    "safari-release-notes": 34,
    "TVMLKit": 348,
    "UserNotifications": 270,
    "ExtensionFoundation": 84,
    "ProximityReader": 1004,
    "MatterSupport": 68,
    "IOBluetooth": 3880,
    "InputMethodKit": 100,
    "AppStoreServerAPI": 219,
    "DeviceManagement": 1221,
    "Hypervisor": 2827,
    "CoreFoundation": 2538,
    "iWorkDocumentExportingAPI": 2,
    "dnssd": 241,
    "PushKit": 26,
    "SCSIControllerDriverKit": 96,
    "watchOS-Apps": 26,
    "AudioUnit": 2,
    "kernel": 39341,
    "ManagedApp": 54,
    "RelevanceKit": 30,
    "ImagePlayground": 85,
    "Observation": 20,
    "CoreAudio": 849,
    "OpenDirectory": 742,
    "MapKitJS": 756,
    "ObjectiveC": 533,
    "SwiftUI": 6520,
    "appstorereceipts": 25,
    "BrowserEngineCore": 16,
    "ScriptingBridge": 31,
    "tvmljs": 268,
    "TVML": 189
}

def verify_index_counts():
    """Verify document counts in Meilisearch index."""
    client = meilisearch.Client(
        os.getenv('MEILI_HTTP_ADDR', 'http://localhost:7700'),
        os.getenv('MEILI_MASTER_KEY', '')
    )
    
    try:
        # Get index stats
        stats = client.index('apple-docs').get_stats()
        total_indexed = stats.get('numberOfDocuments', 0)
        
        console.print(f"\nTotal documents in index: {total_indexed:,}")
        
        # Check counts by framework
        console.print("\nChecking document counts by framework...")
        
        table = Table(title="Framework Document Counts")
        table.add_column("Framework", style="cyan")
        table.add_column("Expected", style="green")
        table.add_column("Indexed", style="yellow")
        table.add_column("Difference", style="red")
        table.add_column("Status", style="blue")
        
        total_expected = sum(EXPECTED_COUNTS.values())
        total_found = 0
        missing_total = 0
        
        for framework, expected in sorted(EXPECTED_COUNTS.items(), key=lambda x: x[1], reverse=True)[:20]:
            # Search for documents with this framework
            result = client.index('apple-docs').search('', {
                'filter': f'framework = "{framework}"',
                'limit': 1
            })
            
            indexed = result.get('estimatedTotalHits', 0)
            total_found += indexed
            diff = indexed - expected
            missing_total += max(0, -diff)
            
            status = "✓" if abs(diff) < 10 else "✗"
            
            table.add_row(
                framework,
                f"{expected:,}",
                f"{indexed:,}",
                f"{diff:+,}",
                status
            )
        
        console.print(table)
        
        console.print(f"\nTotal expected: {total_expected:,}")
        console.print(f"Total found by framework filter: {total_found:,}")
        console.print(f"Total missing: {missing_total:,}")
        
        return total_indexed, total_expected, missing_total
        
    except Exception as e:
        console.print(f"[red]Error connecting to Meilisearch: {e}[/red]")
        return 0, sum(EXPECTED_COUNTS.values()), sum(EXPECTED_COUNTS.values())

if __name__ == "__main__":
    indexed, expected, missing = verify_index_counts()
    
    if missing > 0:
        console.print(f"\n[red]⚠️  Missing {missing:,} documents![/red]")
        sys.exit(1)
    else:
        console.print(f"\n[green]✓ All documents indexed successfully![/green]")
